### PR TITLE
added ndarray-linalg/intel-mkl features

### PR DESCRIPTION
**Pull request by RahulDas-dev**
PR to Fix the issue **link error** [mentioned here](https://github.com/rust-cv/ndarray-vision/issues/50#issue-1087094586)

### CODE REVIEW

**Comment by xd009642** [comment]
The `cargo check --all-features` in CI will now definitely cause issues (and might be causing this one, not sure which check command failed). As the blas features now conflict. I think replacing it with just `cargo check` should be fine - or maybe just removing the check part if it proves annoying and just rely on the `cargo test`

**Comment by RahulDas-dev** [comment]
HI , I am Really Confused, Is there any thing I can do from my end , let me know.

**Comment by xd009642** [comment]
It looks like I can push commits to the PR branch so I'll just quickly try to fix CI so don't worry about it (unless I can't figure it out)

**Comment by xd009642** [comment]
Yeah and that fixed it (apart from coverage job but that's unrelated so I'll merge)

**Pull request merged**
