### PR TITLE
include border in convolution

### PR DESCRIPTION
**Pull request by stefan-k**
This also includes the borders when performing a convolution. It works by extending the original image with zeros in all dimensions.
It creates a temporary array and therefore is less efficient.
Another consequence of this change is that `conv2d` and `conv2d_inplace` now return images of the same size. 

Tests were also adapted.

Ideally one would have to option to choose how borders are handled. For instance one may want to mirror the image at the border.

### CODE REVIEW

**Comment by xd009642** [comment]
Awesome, thanks. 

Yeah so I had a thought on the padding behaviour of having some sort of image padding trait and make it a generic argument to the convolution with a sensible default type. If you want to add that to this PR with the original behaviour and pad with zeros that would be appreciated. If not I can merge and sort it myself 👍

**Comment by xd009642** [comment]
Also PRs are merged into the develop branch, not sure if I ever got to adding a contribution document addressing this, but if you could rebase into develop to remove the 2 release commits that would be appreciated 😊

**Comment by stefan-k** [comment]
Thanks for the feedback. I hope I rebased correctly.
Unfortunately I don't have time to add those features.

**Comment by xd009642** [comment]
Yeah perfect, and don't worry I'll try and add it tonight

**Pull request merged**
